

booster_citizenfront:
    path:     /citizen
    defaults: { _controller: BoosterBundle:Default:citizen }

booster_actor:
    path:     /actor
    defaults: { _controller: BoosterBundle:Default:actor}

