booster_homepage:
    path:     /
    defaults: { _controller: BoosterBundle:Default:index }

booster_citizenfront:
    path:     /citizenfront
    defaults: { _controller: BoosterBundle:Default:index }
