BoosterBundle\Entity\Citizen:
    type: entity
    table: null
    repositoryClass: BoosterBundle\Repository\CitizenRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastname:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        address:
            type: string
            length: 255
        cp:
            type: string
            length: 255
        town:
            type: string
            length: 255
        status:
            type: string
            length: 255
        description:
            type: text
        oneToMany:
            offers:
                targetEntity: BoosterBundle/Entity/Offer
                mappedBy: id
            needs:
                targetEntity: BoosterBundle/Entity/Needs
                mappedBy: id

    lifecycleCallbacks: {  }
