BoosterBundle\Entity\Needs:
    type: entity
    table: null
    repositoryClass: BoosterBundle\Repository\NeedsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        cp:
            type: integer
        town:
            type: string
            length: 255
        description:
            type: text
        activity:
            type: string
            length: 255
        availability:
            type: string
            length: 255
        lat:
            type: integer
        lgt:
            type: integer
    lifecycleCallbacks: {  }
