BoosterBundle\Entity\Needs:
    type: entity
    table: null
    repositoryClass: BoosterBundle\Repository\NeedsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true
        cp:
            type: integer
            nullable: true
        town:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        activity:
            type: string
            length: 255
            nullable: true
        availability:
            type: string
            length: 255
            nullable: true
        lat:
            type: integer
            nullable: true
        lgt:
            type: integer
            nullable: true
    manyToOne:
        users:
            targetEntity: BoosterBundle\Entity\User
            inversedBy: Id
    lifecycleCallbacks: {  }
