BoosterBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        town:
            type: string
            length: 255
        cp:
            type: integer
        address:
            type: string
            length: 255
        phone:
            type: integer
            nullable: true
        resident:
            type: integer
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
        message_mayor:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        lat:
            type: integer
            nullable: true
        lgt:
            type: integer
            nullable: true
        organization:
            type: string
            length: 255
        status_actor:
            type: string
            length: 255
        status_citizen:
            type: string
            length: 255
            nullable: true
        category:
            type: string
            length: 255
        project:
            type: string
            length: 255
            nullable: true

    oneToMany:
        offers:
            targetEntity: BoosterBundle\Entity\Offer
            mappedBy: Id
        needs:
            targetEntity: BoosterBundle\Entity\Needs
            mappedBy: Id

    lifecycleCallbacks: {  }